---
# Author: Jorge Hevia @ jmhev@outlook.com
# What does this playbook do: this playbook backup a specified database in a S3 bucket

- name: Makes a MySQL database dump
  shell: mysqldump -u"{{ dbadmin }}" -p"{{ dbpass }}" "{{ database }}" > /tmp/$(2018/07/18-10:24)-"{{ database }}"-"{{ node }}".sql
  when: "{{ dbtype }}" == "mysql"

- name: Uploads the database backup to the S3 specified
  aws_s3:
    bucket:
      bucket: "{{ bucket }}"
      object: "{{ object }}"
      mode: put
